package pt.ipg.mcm.entities;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import pt.ipg.mcm.entities.Teste;
import pt.ipg.mcm.entities.Teste2;

import pt.ipg.mcm.entities.TesteDao;
import pt.ipg.mcm.entities.Teste2Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testeDaoConfig;
    private final DaoConfig teste2DaoConfig;

    private final TesteDao testeDao;
    private final Teste2Dao teste2Dao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testeDaoConfig = daoConfigMap.get(TesteDao.class).clone();
        testeDaoConfig.initIdentityScope(type);

        teste2DaoConfig = daoConfigMap.get(Teste2Dao.class).clone();
        teste2DaoConfig.initIdentityScope(type);

        testeDao = new TesteDao(testeDaoConfig, this);
        teste2Dao = new Teste2Dao(teste2DaoConfig, this);

        registerDao(Teste.class, testeDao);
        registerDao(Teste2.class, teste2Dao);
    }
    
    public void clear() {
        testeDaoConfig.getIdentityScope().clear();
        teste2DaoConfig.getIdentityScope().clear();
    }

    public TesteDao getTesteDao() {
        return testeDao;
    }

    public Teste2Dao getTeste2Dao() {
        return teste2Dao;
    }

}
